#!/usr/bin/env python3
"""Generate the compact AUROC-only grouped table for the WSDM main text."""
from __future__ import annotations

import json
import math
from pathlib import Path

from rpo_opt_v2_paper_aggregate import (
    EQUAL48_ALL_GRID_HASH,
    EQUAL48_METHOD_GRID_HASHES,
    EQUAL48_PROTOCOL,
    FINAL_SEEDS,
)


REPRO = Path("repro")
SETTINGS = ("ec50_assay|minimol", "ec50_assay|unimol",
            "ic50_assay|minimol", "ic50_assay|unimol")
COLS = ("EC50/Mini", "EC50/Uni", "IC50/Mini", "IC50/Uni", "Macro")
GROUPS = (
    ("Supervision-matched scalar heads", ("RPO", "Balanced BCE", "Pairwise Hinge")),
    ("Classifier-score OE baselines", ("MSP-OE", "ODIN-OE", "Energy-OE")),
    ("Feature-space two-sample diagnostics", ("OE-Mahalanobis", "OE-KNN", "OE-LOF")),
)
NAME = {
    "RPO": r"Mole-PAIR (RPO)",
    "Balanced BCE": "Balanced BCE",
    "Pairwise Hinge": "Pairwise Hinge",
    "MSP-OE": "MSP-OE",
    "ODIN-OE": "ODIN-OE (temperature-only)",
    "Energy-OE": "Energy-OE",
    "OE-Mahalanobis": r"OE-Mahalanobis$^{\dagger}$",
    "OE-KNN": r"OE-KNN$^{\dagger}$",
    "OE-LOF": r"OE-LOF$^{\dagger}$",
}
PAPER_PROTOCOL = "rpo-opt-v2-paper-aggregate-matched-final-seeds"


def validate_summary(summary: dict, source: Path) -> None:
    if summary.get("protocol") != PAPER_PROTOCOL:
        raise ValueError(f"unexpected paper-summary protocol in {source}")
    if tuple(summary.get("final_seeds", ())) != tuple(FINAL_SEEDS):
        raise ValueError(f"paper summary must contain the frozen 20 final seeds: {source}")
    if tuple(summary.get("settings_order", ())) != SETTINGS:
        raise ValueError(f"setting order mismatch in {source}")
    if tuple(summary.get("methods_order", ())) != tuple(NAME):
        raise ValueError(f"method order mismatch in {source}")
    expected_families = [
        {"name": name, "methods": list(methods)} for name, methods in GROUPS
    ]
    if summary.get("method_families") != expected_families:
        raise ValueError(f"method-family grouping mismatch in {source}")
    baseline = summary.get("baseline_source", {})
    if baseline.get("kind") == "equal48":
        expected = {
            "protocol": EQUAL48_PROTOCOL,
            "all_grid_hash": EQUAL48_ALL_GRID_HASH,
            "method_grid_hashes": EQUAL48_METHOD_GRID_HASHES,
            "n_validation_trials_per_method": 48,
            "equal_validation_recipe_budget": True,
        }
        for key, value in expected.items():
            if baseline.get(key) != value:
                raise ValueError(f"equal-48 {key} mismatch in {source}")
    elif baseline.get("kind") != "legacy9-fallback":
        raise ValueError(f"missing or unknown OE baseline source in {source}")
    for setting in SETTINGS:
        if set(summary.get("settings", {}).get(setting, {})) != set(NAME):
            raise ValueError(f"incomplete methods for {setting} in {source}")
    for method in NAME:
        records = [summary["settings"][setting][method]["auroc"] for setting in SETTINGS]
        records.append(summary["macro"][method]["auroc"])
        for rec in records:
            vals = rec.get("values", ())
            if rec.get("n") != len(FINAL_SEEDS) or len(vals) != len(FINAL_SEEDS):
                raise ValueError(f"{method} does not contain 20 paired AUROC values in {source}")
            if not all(math.isfinite(float(value)) for value in vals):
                raise ValueError(f"non-finite AUROC for {method} in {source}")


def values(summary: dict, method: str) -> list[dict]:
    return [summary["settings"][key][method]["auroc"] for key in SETTINGS] + [
        summary["macro"][method]["auroc"]
    ]


def fmt(record: dict, bold: bool) -> str:
    text = rf"{record['mean']:.4f}{{\scriptsize$\pm${record['sd']:.4f}}}"
    return rf"\textbf{{{text}}}" if bold else text


def main() -> None:
    source = REPRO / "rpo_opt_v2_paper_summary.json"
    summary = json.loads(source.read_text())
    validate_summary(summary, source)
    equal48 = summary["baseline_source"]["kind"] == "equal48"
    budget_caption = (
        r"Each method receives exactly 48 method-specific validation recipe trials; "
        if equal48
        else r"The OE rows use the legacy nine-trial validation fallback; "
    )
    lines = [
        "% Auto-generated by rpo_opt_v2_compact_table.py; do not edit by hand.",
        r"\begin{table*}[t]",
        r"\centering",
        r"\small",
        r"\setlength{\tabcolsep}{3.5pt}",
        (
            r"\caption{Supervision-matched AUROC on the DrugOOD assay shifts. All methods "
            + r"use the same frozen representation and auxiliary ID/OOD pools. "
            + budget_caption
            + r"entries are mean $\pm$ sample standard deviation over 20 final seeds. "
            + r"Bold marks the best mean within each method family. "
            + r"$^{\dagger}$Project-defined two-sample diagnostics, not standard named "
            + r"methods from the literature.}"
        ),
        r"\label{tab:matched_oe_compact}",
        r"\begin{tabular}{lccccc}",
        r"\toprule",
        "Method & " + " & ".join(COLS) + r" \\",
        r"\midrule",
    ]
    for group_index, (group, methods) in enumerate(GROUPS):
        lines.append(rf"\multicolumn{{6}}{{l}}{{\emph{{{group}}}}} \\")
        panel = {method: values(summary, method) for method in methods}
        best = [max(panel[method][col]["mean"] for method in methods) for col in range(5)]
        for method in methods:
            cells = [fmt(rec, abs(rec["mean"] - best[col]) < 5e-8)
                     for col, rec in enumerate(panel[method])]
            lines.append(NAME[method] + " & " + " & ".join(cells) + r" \\")
        if group_index != len(GROUPS) - 1:
            lines.append(r"\addlinespace[2pt]")
    lines.extend([r"\bottomrule", r"\end{tabular}", r"\end{table*}", ""])
    target = REPRO / "rpo_opt_v2_compact_table.tex"
    target.write_text("\n".join(lines))
    print(f"WROTE {target}")

    # The main-text table contains the standard learned OE comparisons only.  The
    # project-defined feature-space adaptations remain in the complete table above and
    # in ``rpo_opt_v2_paper_tables.tex``; the caption points to them explicitly rather
    # than silently omitting a stronger diagnostic family.
    main_groups = GROUPS[:2]
    main_lines = [
        "% Auto-generated by rpo_opt_v2_compact_table.py; do not edit by hand.",
        r"\begin{table*}[t]",
        r"\centering",
        r"\small",
        r"\setlength{\tabcolsep}{3.5pt}",
        (
            r"\caption{Supervision-matched learned-detector comparison on the DrugOOD "
            + r"assay shifts. All methods use the same frozen representation and auxiliary "
            + r"ID/OOD pools and receive exactly 48 method-specific validation recipe trials; "
            + r"entries are mean $\pm$ sample standard deviation over 20 final seeds. Bold "
            + r"marks the best mean within each method family. Project-defined feature-space "
            + r"two-sample diagnostics, including stronger cases, are reported separately in "
            + r"Appendix Table~\ref{tab:rpo_oe_v2_all_metrics}.}"
        ),
        r"\label{tab:matched_oe_main}",
        r"\begin{tabular}{lccccc}",
        r"\toprule",
        "Method & " + " & ".join(COLS) + r" \\",
        r"\midrule",
    ]
    for group_index, (group, methods) in enumerate(main_groups):
        main_lines.append(rf"\multicolumn{{6}}{{l}}{{\emph{{{group}}}}} \\")
        panel = {method: values(summary, method) for method in methods}
        best = [max(panel[method][col]["mean"] for method in methods) for col in range(5)]
        for method in methods:
            cells = [
                fmt(rec, abs(rec["mean"] - best[col]) < 5e-8)
                for col, rec in enumerate(panel[method])
            ]
            main_lines.append(NAME[method] + " & " + " & ".join(cells) + r" \\")
        if group_index != len(main_groups) - 1:
            main_lines.append(r"\addlinespace[2pt]")
    main_lines.extend([r"\bottomrule", r"\end{tabular}", r"\end{table*}", ""])
    main_target = REPRO / "rpo_opt_v2_main_table.tex"
    main_target.write_text("\n".join(main_lines))
    print(f"WROTE {main_target}")


if __name__ == "__main__":
    main()
